In [103]:
import pandas as pd 
import numpy as nd 


In [104]:
cd\Users\mahes\Downloads

C:\Users\mahes\Downloads


In [109]:
lend = pd.read_excel('Lending_Data.xlsx')

In [110]:
lend

Name of Lending Institution HQ State Rank TA Ratio1  \
0                                                 NaN      NaN   -1        -2   
1                               American Express Co.       NY     1   0.23829   
2                            First Citizens Banchares      NC     2  0.187393   
3                            Wintrust Financial Corp.      IL     3  0.168999   
4                                       Zions Bancorp      UT     4  0.117973   
..                                                ...      ...  ...       ...   
92                     Charles Schwab Bk                    NV   NR         -   
93                     Third FS&LA                          OH   NR         -   
94  *The bank was formerly known as GE Money Bank,...      NaN  NaN       NaN   
95  1 TA = total domestic assets held by the lende...      NaN  NaN       NaN   
96  Source: U.S. Small Business Administration, Of...      NaN  NaN       NaN   

   TBL Ratio1 Amount ($1,000)  Number      Lender Asset Size  \
0          -3              -4       -5                    -6   
1    0.999544        16350038  3603226  >$50B                  
2     0.49083         3914507   117702  $10B-$50B              
3    0.383561         2842793   136801  $10B-$50B              
4    0.260577         6231770    52612  >$50B                  
..        ...             ...      ...                   ...   
92          -               -        -  >$10B                  
93          -               -        -  >$10B                  
94        NaN             NaN      NaN                   NaN   
95        NaN             NaN      NaN                   NaN   
96        NaN             NaN      NaN                   NaN   

    Amount ($1,000).1  Number .1  Unnamed: 10  Amount ($1,000).2  Number .2  \
0                -7.0       -8.0          NaN               -9.0      -10.0   
1          16318089.0  3603088.0          NaN            31949.0      138.0   
2            378394.0   105081.0          NaN          3536113.0    12621.0   
3            800526.0   126455.0          NaN          2042267.0    10346.0   
4            526206.0    32973.0          NaN          5705564.0    19639.0   
..                ...        ...          ...                ...        ...   
92                0.0        0.0          NaN                0.0        0.0   
93                0.0        0.0          NaN                0.0        0.0   
94                NaN        NaN          NaN                NaN        NaN   
95                NaN        NaN          NaN                NaN        NaN   
96                NaN        NaN          NaN                NaN        NaN   

   CC Amount/TA1  
0            -11  
1           0.28  
2            .    
3              0  
4              0  
..           ...  
92           .    
93           .    
94           NaN  
95           NaN  
96           NaN  

[97 rows x 14 columns]

In [111]:
lend.shape

(97, 14)

In [112]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     object 
 4   TBL Ratio1                   94 non-null     object 
 5   Amount ($1,000)              94 non-null     object 
 6   Number                       94 non-null     object 
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Unnamed: 10                  0 non-null      float64
 11  Amount ($1,000).2            94 non-null     float64
 12  Number .2                    94 non-null     float64
 13  CC Amount/TA1         

In [113]:
del lend['Unnamed: 10']

In [114]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     object 
 4   TBL Ratio1                   94 non-null     object 
 5   Amount ($1,000)              94 non-null     object 
 6   Number                       94 non-null     object 
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object 
dtypes: float64(4), object(

In [115]:
lend['Name of Lending Institution']=lend['Name of Lending Institution'].str.replace(" ","")

In [116]:
lend['Name of Lending Institution'].unique()

array([nan, 'AmericanExpressCo.', 'FirstCitizensBanchares',
       'WintrustFinancialCorp.', 'ZionsBancorp', 'SynovusFinancialCorp.',
       'BB&TCorp.', 'FNBCorp.', 'CapitalOneFinancialCorp.',
       'FultonFinancialCorp.', 'RegionsFinancialCorp.', 'USBancorp.',
       'FirstNiagaraFinancialGrp.', 'LauritzenCorp.',
       'HuntingtonBancsharesInc.', 'BancorpsouthInc.', 'TCFFinancialCorp',
       'GECapitalRetailBk*', 'JPMorganChase&Co', 'Citigroup', 'Popular',
       'HancockHoldingCompany', 'M&TBkCorp', 'BankofAmerCorp',
       'CentralBancompany', 'ArvestBkGrp.', 'CompassBk', 'WellsFargo&Co',
       'PNCFinancialSvc.Group', 'BankofTheWest', 'BMOHarrisBankNA',
       'UmpquaHC', 'TDBkNA', 'Cullen/FrostBkr', 'FirstHorizonNatCorp.',
       'CommerceBancshares', 'SuntrustBk', 'SusquehannaBancshares',
       'AssociatedBancCorp.', 'FifthThirdBancorp', 'Keycorp',
       'ProsperityBancshares', 'FirstmeritCorp.', 'ValleyNatBancorp',
       'WebsterFinancialCorp.', 'PeoplesUnitedBk', 'RBSCi

In [117]:
lend['Rank'].unique()

array([-1, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 'NR', nan],
      dtype=object)

In [118]:
lend['Rank']=lend['Rank'].replace('NR','NaN')

In [119]:
lend['Rank'].unique()

array([-1, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 'NaN', nan],
      dtype=object)

In [120]:
lend['Rank']=lend['Rank'].replace('nan','NaN')

In [121]:
lend['Rank'].unique()

array([-1, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 'NaN', nan],
      dtype=object)

In [122]:
lend

Name of Lending Institution HQ State Rank TA Ratio1  \
0                                                 NaN      NaN   -1        -2   
1                                  AmericanExpressCo.      NY     1   0.23829   
2                              FirstCitizensBanchares      NC     2  0.187393   
3                              WintrustFinancialCorp.      IL     3  0.168999   
4                                        ZionsBancorp      UT     4  0.117973   
..                                                ...      ...  ...       ...   
92                                    CharlesSchwabBk       NV  NaN         -   
93                                         ThirdFS&LA       OH  NaN         -   
94  *ThebankwasformerlyknownasGEMoneyBank,andwasre...      NaN  NaN       NaN   
95  1TA=totaldomesticassetsheldbythelender;TBL=tot...      NaN  NaN       NaN   
96  Source:U.S.SmallBusinessAdministration,Officeo...      NaN  NaN       NaN   

   TBL Ratio1 Amount ($1,000)  Number      Lender Asset Size  \
0          -3              -4       -5                    -6   
1    0.999544        16350038  3603226  >$50B                  
2     0.49083         3914507   117702  $10B-$50B              
3    0.383561         2842793   136801  $10B-$50B              
4    0.260577         6231770    52612  >$50B                  
..        ...             ...      ...                   ...   
92          -               -        -  >$10B                  
93          -               -        -  >$10B                  
94        NaN             NaN      NaN                   NaN   
95        NaN             NaN      NaN                   NaN   
96        NaN             NaN      NaN                   NaN   

    Amount ($1,000).1  Number .1  Amount ($1,000).2  Number .2 CC Amount/TA1  
0                -7.0       -8.0               -9.0      -10.0           -11  
1          16318089.0  3603088.0            31949.0      138.0          0.28  
2            378394.0   105081.0          3536113.0    12621.0           .    
3            800526.0   126455.0          2042267.0    10346.0             0  
4            526206.0    32973.0          5705564.0    19639.0             0  
..                ...        ...                ...        ...           ...  
92                0.0        0.0                0.0        0.0           .    
93                0.0        0.0                0.0        0.0           .    
94                NaN        NaN                NaN        NaN           NaN  
95                NaN        NaN                NaN        NaN           NaN  
96                NaN        NaN                NaN        NaN           NaN  

[97 rows x 13 columns]

In [123]:
lend['TA Ratio1'].unique()

array([-2, 0.23829000111391208, 0.18739273526410935, 0.16899882809831798,
       0.11797264925046931, 0.16233301092034935, 0.05346012640256642,
       0.1276719718460003, 0.027559685122363675, 0.12912579445744454,
       0.061038849745431764, 0.04210903728015195, 0.07217294726958355,
       0.07050788760752706, 0.06938331614573934, 0.12527060543171153,
       0.09360439445798256, 0.04224121728443015, 0.01860559808546651,
       0.012517432629402586, 0.07086614263787584, 0.09230769870674804,
       0.06775485242139456, 0.019830772196350342, 0.10959884745118673,
       0.08567778172351002, 0.04853389342247428, 0.028648540378098702,
       0.03639142784113918, 0.04676469443587367, 0.04175573550067276,
       0.10977025478672768, 0.029723405918041342, 0.06745437928906182,
       0.05208094284818372, 0.051392971043785166, 0.0359221958734165,
       0.06809885337387321, 0.05865818884042475, 0.03530193724692176,
       0.03841558206749967, 0.06515382339028943, 0.0779389099421068,
       0.073

In [124]:
lend['TA Ratio1']= lend['TA Ratio1'].replace('-','NaN')

In [125]:
lend['TA Ratio1'].unique()

array([-2, 0.23829000111391208, 0.18739273526410935, 0.16899882809831798,
       0.11797264925046931, 0.16233301092034935, 0.05346012640256642,
       0.1276719718460003, 0.027559685122363675, 0.12912579445744454,
       0.061038849745431764, 0.04210903728015195, 0.07217294726958355,
       0.07050788760752706, 0.06938331614573934, 0.12527060543171153,
       0.09360439445798256, 0.04224121728443015, 0.01860559808546651,
       0.012517432629402586, 0.07086614263787584, 0.09230769870674804,
       0.06775485242139456, 0.019830772196350342, 0.10959884745118673,
       0.08567778172351002, 0.04853389342247428, 0.028648540378098702,
       0.03639142784113918, 0.04676469443587367, 0.04175573550067276,
       0.10977025478672768, 0.029723405918041342, 0.06745437928906182,
       0.05208094284818372, 0.051392971043785166, 0.0359221958734165,
       0.06809885337387321, 0.05865818884042475, 0.03530193724692176,
       0.03841558206749967, 0.06515382339028943, 0.0779389099421068,
       0.073

In [126]:
lend['TA Ratio1']= lend['TA Ratio1'].replace('nan','NaN')

In [127]:
lend['TA Ratio1'].unique()

array([-2, 0.23829000111391208, 0.18739273526410935, 0.16899882809831798,
       0.11797264925046931, 0.16233301092034935, 0.05346012640256642,
       0.1276719718460003, 0.027559685122363675, 0.12912579445744454,
       0.061038849745431764, 0.04210903728015195, 0.07217294726958355,
       0.07050788760752706, 0.06938331614573934, 0.12527060543171153,
       0.09360439445798256, 0.04224121728443015, 0.01860559808546651,
       0.012517432629402586, 0.07086614263787584, 0.09230769870674804,
       0.06775485242139456, 0.019830772196350342, 0.10959884745118673,
       0.08567778172351002, 0.04853389342247428, 0.028648540378098702,
       0.03639142784113918, 0.04676469443587367, 0.04175573550067276,
       0.10977025478672768, 0.029723405918041342, 0.06745437928906182,
       0.05208094284818372, 0.051392971043785166, 0.0359221958734165,
       0.06809885337387321, 0.05865818884042475, 0.03530193724692176,
       0.03841558206749967, 0.06515382339028943, 0.0779389099421068,
       0.073

In [128]:
m

0.024802665291797955

In [129]:
lend['TA Ratio1']=lend['TA Ratio1'].replace('NaN',0)

In [130]:
lend['TA Ratio1'].unique()

array([-2.00000000e+00,  2.38290001e-01,  1.87392735e-01,  1.68998828e-01,
        1.17972649e-01,  1.62333011e-01,  5.34601264e-02,  1.27671972e-01,
        2.75596851e-02,  1.29125794e-01,  6.10388497e-02,  4.21090373e-02,
        7.21729473e-02,  7.05078876e-02,  6.93833161e-02,  1.25270605e-01,
        9.36043945e-02,  4.22412173e-02,  1.86055981e-02,  1.25174326e-02,
        7.08661426e-02,  9.23076987e-02,  6.77548524e-02,  1.98307722e-02,
        1.09598847e-01,  8.56777817e-02,  4.85338934e-02,  2.86485404e-02,
        3.63914278e-02,  4.67646944e-02,  4.17557355e-02,  1.09770255e-01,
        2.97234059e-02,  6.74543793e-02,  5.20809428e-02,  5.13929710e-02,
        3.59221959e-02,  6.80988534e-02,  5.86581888e-02,  3.53019372e-02,
        3.84155821e-02,  6.51538234e-02,  7.79389099e-02,  7.37621636e-02,
        5.72970642e-02,  6.64999259e-02,  2.30146460e-02,  3.22754788e-02,
        2.89904366e-03,  6.49990685e-02,  4.59981320e-02,  2.24942211e-02,
        6.30667535e-02,  

In [131]:
m=lend['TA Ratio1'].mean()

In [132]:
m

0.024802665291797955

In [133]:
lend['TA Ratio1']=lend['TA Ratio1'].replace(0,m)

In [134]:
lend['TA Ratio1'].

SyntaxError: invalid syntax (2281560854.py, line 1)

In [135]:
lend['TA Ratio1'].value_counts()

0.024803    5
0.006365    1
0.019009    1
0.031035    1
0.015879    1
           ..
0.036391    1
0.028649    1
0.048534    1
0.085678    1
0.066500    1
Name: TA Ratio1, Length: 90, dtype: int64

In [136]:
lend['TBL Ratio1'].unique()

array([-3, 0.9995438789267235, 0.49083003982305323, 0.3835613573528858,
       0.2605768326937982, 0.381387272420679, 0.25296565578166397,
       0.41620727969100085, 0.31646647630840374, 0.3476107564641037,
       0.21917630439062924, 0.2048450644551371, 0.28784641979139347,
       0.33721222743318624, 0.2220126204536733, 0.40350622183896606,
       0.3695863238877056, 1, 0.2187234348911782, 0.26205738553793306,
       0.2575450870308851, 0.298702148661442, 0.17818240197188204,
       0.18193001051122903, 0.3891192126353021, 0.3453518246543522,
       0.1717472225328084, 0.1457837843076052, 0.14276361616838146,
       0.20869240076092224, 0.20061145903307862, 0.2548147876377126,
       0.19244733731360394, 0.2378382668710881, 0.21271594111229034,
       0.2675006215122049, 0.14245552397018366, 0.22230239918177036,
       0.19129209614490553, 0.1141507081833066, 0.13937752951839222,
       0.40516250561488415, 0.2177206060298806, 0.20760834284075647,
       0.22233802171270448, 0.15679

In [137]:
lend['TBL Ratio1']=lend['TBL Ratio1'].replace('-',0)

In [138]:
lend['TBL Ratio1'].unique()

array([-3.00000000e+00,  9.99543879e-01,  4.90830040e-01,  3.83561357e-01,
        2.60576833e-01,  3.81387272e-01,  2.52965656e-01,  4.16207280e-01,
        3.16466476e-01,  3.47610756e-01,  2.19176304e-01,  2.04845064e-01,
        2.87846420e-01,  3.37212227e-01,  2.22012620e-01,  4.03506222e-01,
        3.69586324e-01,  1.00000000e+00,  2.18723435e-01,  2.62057386e-01,
        2.57545087e-01,  2.98702149e-01,  1.78182402e-01,  1.81930011e-01,
        3.89119213e-01,  3.45351825e-01,  1.71747223e-01,  1.45783784e-01,
        1.42763616e-01,  2.08692401e-01,  2.00611459e-01,  2.54814788e-01,
        1.92447337e-01,  2.37838267e-01,  2.12715941e-01,  2.67500622e-01,
        1.42455524e-01,  2.22302399e-01,  1.91292096e-01,  1.14150708e-01,
        1.39377530e-01,  4.05162506e-01,  2.17720606e-01,  2.07608343e-01,
        2.22338022e-01,  1.56795691e-01,  1.07544483e-01,  1.25575354e-01,
        1.60156054e-01,  8.88724694e-02,  6.58310688e-02,  1.82552611e-01,
        3.07857191e-01,  

In [139]:
lend['TBL Ratio1']=lend['TBL Ratio1'].replace(0,lend['TBL Ratio1'].mean())

In [140]:
lend['TBL Ratio1']

0    -3.000000
1     0.999544
2     0.490830
3     0.383561
4     0.260577
        ...   
92    0.203248
93    0.203248
94         NaN
95         NaN
96         NaN
Name: TBL Ratio1, Length: 97, dtype: float64

In [141]:
lend

Name of Lending Institution HQ State Rank  \
0                                                 NaN      NaN   -1   
1                                  AmericanExpressCo.      NY     1   
2                              FirstCitizensBanchares      NC     2   
3                              WintrustFinancialCorp.      IL     3   
4                                        ZionsBancorp      UT     4   
..                                                ...      ...  ...   
92                                    CharlesSchwabBk       NV  NaN   
93                                         ThirdFS&LA       OH  NaN   
94  *ThebankwasformerlyknownasGEMoneyBank,andwasre...      NaN  NaN   
95  1TA=totaldomesticassetsheldbythelender;TBL=tot...      NaN  NaN   
96  Source:U.S.SmallBusinessAdministration,Officeo...      NaN  NaN   

    TA Ratio1  TBL Ratio1 Amount ($1,000)  Number      Lender Asset Size  \
0   -2.000000   -3.000000              -4       -5                    -6   
1    0.238290    0.999544        16350038  3603226  >$50B                  
2    0.187393    0.490830         3914507   117702  $10B-$50B              
3    0.168999    0.383561         2842793   136801  $10B-$50B              
4    0.117973    0.260577         6231770    52612  >$50B                  
..        ...         ...             ...      ...                   ...   
92   0.024803    0.203248               -        -  >$10B                  
93   0.024803    0.203248               -        -  >$10B                  
94        NaN         NaN             NaN      NaN                   NaN   
95        NaN         NaN             NaN      NaN                   NaN   
96        NaN         NaN             NaN      NaN                   NaN   

    Amount ($1,000).1  Number .1  Amount ($1,000).2  Number .2 CC Amount/TA1  
0                -7.0       -8.0               -9.0      -10.0           -11  
1          16318089.0  3603088.0            31949.0      138.0          0.28  
2            378394.0   105081.0          3536113.0    12621.0           .    
3            800526.0   126455.0          2042267.0    10346.0             0  
4            526206.0    32973.0          5705564.0    19639.0             0  
..                ...        ...                ...        ...           ...  
92                0.0        0.0                0.0        0.0           .    
93                0.0        0.0                0.0        0.0           .    
94                NaN        NaN                NaN        NaN           NaN  
95                NaN        NaN                NaN        NaN           NaN  
96                NaN        NaN                NaN        NaN           NaN  

[97 rows x 13 columns]

In [142]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     float64
 4   TBL Ratio1                   94 non-null     float64
 5   Amount ($1,000)              94 non-null     object 
 6   Number                       94 non-null     object 
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object 
dtypes: float64(6), object(

In [143]:
lend['Amount ($1,000)'].unique()

array([-4, 16350038, 3914507, 2842793, 6231770, 4227168, 9408732, 1475506,
       9105726, 2133209, 7386970, 14632161, 2530706, 1142096, 3914846,
       1646169, 1676064, 1133624, 25003294, 9081426, 2464690, 1775410,
       5560491, 31042181, 1113344, 1167974, 3445358, 34570389, 10537942,
       3645716, 3849439, 1264035, 6197769, 1411367, 1315603, 1058791,
       6179640, 1221505, 1279224, 4051406, 3186664, 699037, 1138055,
       1180078, 1111695, 1856969, 3241138, 2796643, 206777, 1350924,
       2839695, 1964564, 758549, 434896, 114360, 599000, 684053, 707069,
       735067, 478638, 658569, 959892, 607796, 1372869, 381448, 256052,
       163053, 1126858, 174663, 64835, 169440, 42358, 390367, 588440,
       514444, 446034, 636415, 436, 180865, 495681, 317825, 159411,
       141181, 261157, 94100, 107724, 55544, 4000, 2000, 0, '-', nan],
      dtype=object)

In [144]:
lend['Amount ($1,000)']=lend['Amount ($1,000)'].replace('-',0)

In [145]:
lend['Amount ($1,000)']

0           -4.0
1     16350038.0
2      3914507.0
3      2842793.0
4      6231770.0
         ...    
92           0.0
93           0.0
94           NaN
95           NaN
96           NaN
Name: Amount ($1,000), Length: 97, dtype: float64

In [146]:
lend['Amount ($1,000)']=lend['Amount ($1,000)'].replace(0,lend['Amount ($1,000)'].mean())

In [147]:
lend['Amount ($1,000)']

0    -4.000000e+00
1     1.635004e+07
2     3.914507e+06
3     2.842793e+06
4     6.231770e+06
          ...     
92    3.015387e+06
93    3.015387e+06
94             NaN
95             NaN
96             NaN
Name: Amount ($1,000), Length: 97, dtype: float64

In [148]:
lend

Name of Lending Institution HQ State Rank  \
0                                                 NaN      NaN   -1   
1                                  AmericanExpressCo.      NY     1   
2                              FirstCitizensBanchares      NC     2   
3                              WintrustFinancialCorp.      IL     3   
4                                        ZionsBancorp      UT     4   
..                                                ...      ...  ...   
92                                    CharlesSchwabBk       NV  NaN   
93                                         ThirdFS&LA       OH  NaN   
94  *ThebankwasformerlyknownasGEMoneyBank,andwasre...      NaN  NaN   
95  1TA=totaldomesticassetsheldbythelender;TBL=tot...      NaN  NaN   
96  Source:U.S.SmallBusinessAdministration,Officeo...      NaN  NaN   

    TA Ratio1  TBL Ratio1  Amount ($1,000)  Number      Lender Asset Size  \
0   -2.000000   -3.000000    -4.000000e+00       -5                    -6   
1    0.238290    0.999544     1.635004e+07  3603226  >$50B                  
2    0.187393    0.490830     3.914507e+06   117702  $10B-$50B              
3    0.168999    0.383561     2.842793e+06   136801  $10B-$50B              
4    0.117973    0.260577     6.231770e+06    52612  >$50B                  
..        ...         ...              ...      ...                   ...   
92   0.024803    0.203248     3.015387e+06        -  >$10B                  
93   0.024803    0.203248     3.015387e+06        -  >$10B                  
94        NaN         NaN              NaN      NaN                   NaN   
95        NaN         NaN              NaN      NaN                   NaN   
96        NaN         NaN              NaN      NaN                   NaN   

    Amount ($1,000).1  Number .1  Amount ($1,000).2  Number .2 CC Amount/TA1  
0                -7.0       -8.0               -9.0      -10.0           -11  
1          16318089.0  3603088.0            31949.0      138.0          0.28  
2            378394.0   105081.0          3536113.0    12621.0           .    
3            800526.0   126455.0          2042267.0    10346.0             0  
4            526206.0    32973.0          5705564.0    19639.0             0  
..                ...        ...                ...        ...           ...  
92                0.0        0.0                0.0        0.0           .    
93                0.0        0.0                0.0        0.0           .    
94                NaN        NaN                NaN        NaN           NaN  
95                NaN        NaN                NaN        NaN           NaN  
96                NaN        NaN                NaN        NaN           NaN  

[97 rows x 13 columns]

In [149]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     float64
 4   TBL Ratio1                   94 non-null     float64
 5   Amount ($1,000)              94 non-null     float64
 6   Number                       94 non-null     object 
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object 
dtypes: float64(7), object(

In [150]:
lend['Number '].unique()

array([-5, 3603226, 117702, 136801, 52612, 22675, 506879, 25011, 2914573,
       20080, 63394, 870931, 32530, 101941, 34732, 15882, 19823, 716231,
       2893892, 1746916, 22703, 18706, 56151, 3277274, 14445, 14601,
       169539, 617508, 220200, 38919, 46887, 9351, 56364, 11708, 27253,
       25561, 57543, 10307, 28926, 71778, 58231, 4936, 6599, 5034, 13799,
       12948, 62262, 34502, 112259, 5039, 16366, 68244, 5125, 7076, 26447,
       9943, 4552, 3134, 17830, 4230, 3136, 4390, 2919, 11632, 3098, 3820,
       18808, 19558, 984, 121, 710, 86, 5182, 1765, 3595, 2086, 2773, 2,
       717, 1410, 1239, 652, 486, 834, 405, 406, 351, 6, 4, 1, '-', nan],
      dtype=object)

In [151]:
lend['Number ']=lend['Number '].replace('-',0)

In [152]:
lend['Number '].unique()

array([-5.000000e+00,  3.603226e+06,  1.177020e+05,  1.368010e+05,
        5.261200e+04,  2.267500e+04,  5.068790e+05,  2.501100e+04,
        2.914573e+06,  2.008000e+04,  6.339400e+04,  8.709310e+05,
        3.253000e+04,  1.019410e+05,  3.473200e+04,  1.588200e+04,
        1.982300e+04,  7.162310e+05,  2.893892e+06,  1.746916e+06,
        2.270300e+04,  1.870600e+04,  5.615100e+04,  3.277274e+06,
        1.444500e+04,  1.460100e+04,  1.695390e+05,  6.175080e+05,
        2.202000e+05,  3.891900e+04,  4.688700e+04,  9.351000e+03,
        5.636400e+04,  1.170800e+04,  2.725300e+04,  2.556100e+04,
        5.754300e+04,  1.030700e+04,  2.892600e+04,  7.177800e+04,
        5.823100e+04,  4.936000e+03,  6.599000e+03,  5.034000e+03,
        1.379900e+04,  1.294800e+04,  6.226200e+04,  3.450200e+04,
        1.122590e+05,  5.039000e+03,  1.636600e+04,  6.824400e+04,
        5.125000e+03,  7.076000e+03,  2.644700e+04,  9.943000e+03,
        4.552000e+03,  3.134000e+03,  1.783000e+04,  4.230000e

In [153]:
lend['Number ']=lend['Number '].replace(0,lend['Number '].mean())

In [154]:
lend['Number ']

0    -5.000000e+00
1     3.603226e+06
2     1.177020e+05
3     1.368010e+05
4     5.261200e+04
          ...     
92    2.049073e+05
93    2.049073e+05
94             NaN
95             NaN
96             NaN
Name: Number , Length: 97, dtype: float64

In [155]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     float64
 4   TBL Ratio1                   94 non-null     float64
 5   Amount ($1,000)              94 non-null     float64
 6   Number                       94 non-null     float64
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object 
dtypes: float64(8), object(

In [156]:
lend['CC Amount/TA1'].unique()

array([-11, 0.28, '    .  ', 0, 0.01, 0.25, 0.05, 0.06, 0.1, 0.03, 0.07,
       0.02, nan], dtype=object)

In [157]:
lend['CC Amount/TA1']=lend['CC Amount/TA1'].replace('    .  ',0)

In [158]:
lend['CC Amount/TA1'].unique()

array([-1.1e+01,  2.8e-01,  0.0e+00,  1.0e-02,  2.5e-01,  5.0e-02,
        6.0e-02,  1.0e-01,  3.0e-02,  7.0e-02,  2.0e-02,      nan])

In [159]:
lend

Name of Lending Institution HQ State Rank  \
0                                                 NaN      NaN   -1   
1                                  AmericanExpressCo.      NY     1   
2                              FirstCitizensBanchares      NC     2   
3                              WintrustFinancialCorp.      IL     3   
4                                        ZionsBancorp      UT     4   
..                                                ...      ...  ...   
92                                    CharlesSchwabBk       NV  NaN   
93                                         ThirdFS&LA       OH  NaN   
94  *ThebankwasformerlyknownasGEMoneyBank,andwasre...      NaN  NaN   
95  1TA=totaldomesticassetsheldbythelender;TBL=tot...      NaN  NaN   
96  Source:U.S.SmallBusinessAdministration,Officeo...      NaN  NaN   

    TA Ratio1  TBL Ratio1  Amount ($1,000)       Number   \
0   -2.000000   -3.000000    -4.000000e+00 -5.000000e+00   
1    0.238290    0.999544     1.635004e+07  3.603226e+06   
2    0.187393    0.490830     3.914507e+06  1.177020e+05   
3    0.168999    0.383561     2.842793e+06  1.368010e+05   
4    0.117973    0.260577     6.231770e+06  5.261200e+04   
..        ...         ...              ...           ...   
92   0.024803    0.203248     3.015387e+06  2.049073e+05   
93   0.024803    0.203248     3.015387e+06  2.049073e+05   
94        NaN         NaN              NaN           NaN   
95        NaN         NaN              NaN           NaN   
96        NaN         NaN              NaN           NaN   

       Lender Asset Size  Amount ($1,000).1  Number .1  Amount ($1,000).2  \
0                     -6               -7.0       -8.0               -9.0   
1   >$50B                        16318089.0  3603088.0            31949.0   
2   $10B-$50B                      378394.0   105081.0          3536113.0   
3   $10B-$50B                      800526.0   126455.0          2042267.0   
4   >$50B                          526206.0    32973.0          5705564.0   
..                   ...                ...        ...                ...   
92  >$10B                               0.0        0.0                0.0   
93  >$10B                               0.0        0.0                0.0   
94                   NaN                NaN        NaN                NaN   
95                   NaN                NaN        NaN                NaN   
96                   NaN                NaN        NaN                NaN   

    Number .2  CC Amount/TA1  
0       -10.0         -11.00  
1       138.0           0.28  
2     12621.0           0.00  
3     10346.0           0.00  
4     19639.0           0.00  
..        ...            ...  
92        0.0           0.00  
93        0.0           0.00  
94        NaN            NaN  
95        NaN            NaN  
96        NaN            NaN  

[97 rows x 13 columns]

In [160]:
lend.dropna()

Name of Lending Institution HQ State Rank  TA Ratio1  TBL Ratio1  \
1           AmericanExpressCo.      NY     1   0.238290    0.999544   
2       FirstCitizensBanchares      NC     2   0.187393    0.490830   
3       WintrustFinancialCorp.      IL     3   0.168999    0.383561   
4                 ZionsBancorp      UT     4   0.117973    0.260577   
5        SynovusFinancialCorp.      GA     5   0.162333    0.381387   
..                         ...      ...  ...        ...         ...   
89                USAASvg.Bank       NV  NaN   0.024803    0.203248   
90            StateStreetCorp.      MA   NaN   0.024803    0.203248   
91                    ETradeBk       VA  NaN   0.024803    0.203248   
92             CharlesSchwabBk       NV  NaN   0.024803    0.203248   
93                  ThirdFS&LA       OH  NaN   0.024803    0.203248   

    Amount ($1,000)       Number      Lender Asset Size  Amount ($1,000).1  \
1      1.635004e+07  3.603226e+06  >$50B                        16318089.0   
2      3.914507e+06  1.177020e+05  $10B-$50B                      378394.0   
3      2.842793e+06  1.368010e+05  $10B-$50B                      800526.0   
4      6.231770e+06  5.261200e+04  >$50B                          526206.0   
5      4.227168e+06  2.267500e+04  $10B-$50B                      539666.0   
..              ...           ...                   ...                ...   
89     3.015387e+06  1.000000e+00  >$10B                               0.0   
90     3.015387e+06  2.049073e+05  >$50B                               0.0   
91     3.015387e+06  2.049073e+05  >$10B                               0.0   
92     3.015387e+06  2.049073e+05  >$10B                               0.0   
93     3.015387e+06  2.049073e+05  >$10B                               0.0   

    Number .1  Amount ($1,000).2  Number .2  CC Amount/TA1  
1   3603088.0            31949.0      138.0           0.28  
2    105081.0          3536113.0    12621.0           0.00  
3    126455.0          2042267.0    10346.0           0.00  
4     32973.0          5705564.0    19639.0           0.00  
5      9593.0          3687502.0    13082.0           0.01  
..        ...                ...        ...            ...  
89        1.0                0.0        0.0           0.00  
90        0.0                0.0        0.0           0.00  
91        0.0                0.0        0.0           0.00  
92        0.0                0.0        0.0           0.00  
93        0.0                0.0        0.0           0.00  

[93 rows x 13 columns]

In [161]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     float64
 4   TBL Ratio1                   94 non-null     float64
 5   Amount ($1,000)              94 non-null     float64
 6   Number                       94 non-null     float64
 7   Lender Asset Size            94 non-null     object 
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     float64
dtypes: float64(9), object(

In [162]:
lend['Lender Asset Size'].unique()

array([-6, '>$50B               ', '$10B-$50B           ',
       '>$10B               ', nan], dtype=object)

In [163]:
lend['Lender Asset Size'].value_counts()

$10B-$50B               43
>$50B                   32
>$10B                   18
-6                       1
Name: Lender Asset Size, dtype: int64

In [164]:
lend['Lender Asset Size']=lend['Lender Asset Size'].str.replace(" ","")

In [165]:
lend['Lender Asset Size'].unique()

array([nan, '>$50B', '$10B-$50B', '>$10B'], dtype=object)

In [166]:
lend['Lender Asset Size'].dropna()

1         >$50B
2     $10B-$50B
3     $10B-$50B
4         >$50B
5     $10B-$50B
        ...    
89        >$10B
90        >$50B
91        >$10B
92        >$10B
93        >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [167]:
from sklearn.preprocessing import LabelEncoder             

In [168]:
le = LabelEncoder()

In [169]:
lend['Lender Asset Size']=le.fit_transform(lend['Lender Asset Size'])

In [170]:
lend['Lender Asset Size']

0     3
1     2
2     0
3     0
4     2
     ..
92    1
93    1
94    3
95    3
96    3
Name: Lender Asset Size, Length: 97, dtype: int32

In [173]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  96 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         94 non-null     object 
 3   TA Ratio1                    94 non-null     float64
 4   TBL Ratio1                   94 non-null     float64
 5   Amount ($1,000)              94 non-null     float64
 6   Number                       94 non-null     float64
 7   Lender Asset Size            97 non-null     int32  
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     float64
dtypes: float64(9), int32(1

In [174]:
lend.dropna(axis=0, inplace=True)

In [175]:
lend

Name of Lending Institution HQ State Rank  TA Ratio1  TBL Ratio1  \
1           AmericanExpressCo.      NY     1   0.238290    0.999544   
2       FirstCitizensBanchares      NC     2   0.187393    0.490830   
3       WintrustFinancialCorp.      IL     3   0.168999    0.383561   
4                 ZionsBancorp      UT     4   0.117973    0.260577   
5        SynovusFinancialCorp.      GA     5   0.162333    0.381387   
..                         ...      ...  ...        ...         ...   
89                USAASvg.Bank       NV  NaN   0.024803    0.203248   
90            StateStreetCorp.      MA   NaN   0.024803    0.203248   
91                    ETradeBk       VA  NaN   0.024803    0.203248   
92             CharlesSchwabBk       NV  NaN   0.024803    0.203248   
93                  ThirdFS&LA       OH  NaN   0.024803    0.203248   

    Amount ($1,000)       Number   Lender Asset Size  Amount ($1,000).1  \
1      1.635004e+07  3.603226e+06                  2         16318089.0   
2      3.914507e+06  1.177020e+05                  0           378394.0   
3      2.842793e+06  1.368010e+05                  0           800526.0   
4      6.231770e+06  5.261200e+04                  2           526206.0   
5      4.227168e+06  2.267500e+04                  0           539666.0   
..              ...           ...                ...                ...   
89     3.015387e+06  1.000000e+00                  1                0.0   
90     3.015387e+06  2.049073e+05                  2                0.0   
91     3.015387e+06  2.049073e+05                  1                0.0   
92     3.015387e+06  2.049073e+05                  1                0.0   
93     3.015387e+06  2.049073e+05                  1                0.0   

    Number .1  Amount ($1,000).2  Number .2  CC Amount/TA1  
1   3603088.0            31949.0      138.0           0.28  
2    105081.0          3536113.0    12621.0           0.00  
3    126455.0          2042267.0    10346.0           0.00  
4     32973.0          5705564.0    19639.0           0.00  
5      9593.0          3687502.0    13082.0           0.01  
..        ...                ...        ...            ...  
89        1.0                0.0        0.0           0.00  
90        0.0                0.0        0.0           0.00  
91        0.0                0.0        0.0           0.00  
92        0.0                0.0        0.0           0.00  
93        0.0                0.0        0.0           0.00  

[93 rows x 13 columns]

In [176]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Name of Lending Institution  93 non-null     object 
 1   HQ State                     93 non-null     object 
 2   Rank                         93 non-null     object 
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int32  
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     float64
dtypes: float64(9), int32(1